# Generated by Django 5.2.3 on 2026-07-11 18:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_branch_inventory_branch_sale_branch_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10, help_text='Triggers low-stock alert when quantity falls at or below this.'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, help_text='Scannable SKU/barcode identifier.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, help_text='Clinical/active-ingredient name.', max_length=150),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_controlled_substance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('branch_manager', 'Branch Manager'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('inventory_manager', 'Inventory Manager')], default='cashier', max_length=20),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_license_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Doctor license must match the format XX-NNNNN (e.g., PPB-102345).', regex='^[A-Z]{2,4}-\\d{4,8}$')])),
                ('diagnosis_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='pos.branch')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='pos.customer')),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validated_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_instructions', models.CharField(max_length=255)),
                ('quantity_per_refill', models.PositiveIntegerField()),
                ('refill_interval_days', models.PositiveIntegerField(default=30, help_text='Days between authorized refills.')),
                ('total_refills_allowed', models.PositiveIntegerField(default=1)),
                ('refills_used', models.PositiveIntegerField(default=0)),
                ('last_dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='DispensingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('interaction_warning_acknowledged', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_logs', to='pos.branch')),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_actions', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_logs', to='pos.sale')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_logs', to='pos.prescriptionitem')),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=20)),
                ('description', models.TextField(help_text='Clinical explanation of the interaction risk.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='pos.medicine')),
                ('medicine_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='pos.medicine')),
            ],
            options={
                'unique_together': {('medicine_a', 'medicine_b')},
            },
        ),
    ]
